apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/ambrish24/catalog-service/k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: catalog-config

images:
- name: catalog-service
  newName: ghcr.io/ambrish24/catalog-service
  newTag: 2fbf1877ed89b6afb26ca30ee211e4991d2dc939

replicas:
- count: 2
  name: catalog-service
